### ISSUE TITLE
Typedefs, can we have them?

### ISSUE THREAD

**Issue by meh** [bagucode/clj-native#6]
It would be useful if there was a way to add typedefs.

I'm new to Clojure so maybe there's some magic way to have them, but well, I won't find out unless I ask.

Thanks.

**Comment by bagucode** [comment]
Please explain your use case, I suspect that what you want to do is already possible but I won't know unless I understand what is that you want ;)
In clj-native there is no use for typedef support since typedef is just an alias and the information needed by clj-native is the in-memory structure of types, not their names. You can pick any name you want on the Clojure side.

**Comment by meh** [comment]
My usecase is bindings for Xlib, there's a `XID` type that is a typedef to `unsigned long`.

**Comment by bagucode** [comment]
Just use long in the c-lib definition on the Clojure side. There are no unsigned primitives in the JVM but as long as you don't do any calculations with the value in Clojure then it won't matter if the value is signed on the JVM side and unsigned on the C side because they will still be bit-identical so for an identifier it should work fine.

**Comment by meh** [comment]
The point is knowing when something requires a XID when you see it, it's the whole point of typedefs.

**Comment by bagucode** [comment]
Yes, you do have a point. But I am not actively developing clj-native so I will not add any new features. I do fix bugs occasionally and pull requests are welcome if they are easily understandable and come with tests.
I can think of two workarounds off the top of my head:
1. Make a better documented wrapper function in Clojure that just calls the function defined in the c-lib form.
2. Define a struct in your c-lib form named XID that has a single field of type long and use that wherever the C code uses XID.
